name: CD-production

on:
  push:
    branches:
    - main

jobs:
  prod-deploy:
      name: Deploy Functions in Production Environment
      runs-on: ubuntu-latest
      environment: production

      steps:

      - name: LS
        run: ls

      - name: Checkout
        uses: actions/checkout@v2 

      - name: LS
        run: pwd && ls
        
      - name: Build
        run: npm install

      - name: Firebase Deploy
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
