name: CD-prod

on:
  push:
    branches:
    - main

jobs:
  prod-deploy:
      name: Deploy Functions in Production Environment
      runs-on: ubuntu-latest
      container: node:16.14.2
      environment: production

      steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: check node version
        run: node -v

      - name: install sudo
        run: apt-get update && apt-get install sudo
        
      - name: Build
        run: cd functions && npm install

      - name: Firebase Deploy
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only functions:api
